name: mini-pascal
version: 1.0.0
summary: A Mini-Pascal compiler
description: A Mini-Pascal compiler
confinement: devmode
grade: devel

apps:
    mini-pascal:
        environment:
            LC_ALL: "C.UTF-8"
        command: usr/bin/mini-pascal

parts:
    install-jdk:
        plugin: jdk
        source: .

    mini-pascal:
        plugin: make
        source: https://github.com/jevan0307/extended-minipascal-compiler
        source-type: git
        build-packages:
            - g++
            - flex
            - bison
            - libboost-filesystem-dev
            - libboost-system-dev
            - libboost-program-options-dev
        after:
            - install-jdk
